"""add_role_to_users

Revision ID: ec82222d23a2
Revises: 0003
Create Date: 2026-08-04 13:39:49.586293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec82222d23a2'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('superstore_sales', 'postal_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False, server_default='viewer'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # Remove duplicate drop_index
    op.alter_column('superstore_sales', 'postal_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
