"""add_role_to_users

Revision ID: ec82222d23a2
Revises: 0003
Create Date: 2026-08-04 13:39:49.586293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec82222d23a2'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('superstore_sales', 'postal_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('ix_superstore_sales_category'), 'superstore_sales', ['category'], unique=False)
    op.create_index(op.f('ix_superstore_sales_city'), 'superstore_sales', ['city'], unique=False)
    op.create_index(op.f('ix_superstore_sales_region'), 'superstore_sales', ['region'], unique=False)
    op.create_index(op.f('ix_superstore_sales_segment'), 'superstore_sales', ['segment'], unique=False)
    op.create_index(op.f('ix_superstore_sales_state'), 'superstore_sales', ['state'], unique=False)
    op.create_index(op.f('ix_superstore_sales_sub_category'), 'superstore_sales', ['sub_category'], unique=False)
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False, server_default='viewer'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_superstore_sales_sub_category'), table_name='superstore_sales')
    op.drop_index(op.f('ix_superstore_sales_state'), table_name='superstore_sales')
    op.drop_index(op.f('ix_superstore_sales_segment'), table_name='superstore_sales')
    op.drop_index(op.f('ix_superstore_sales_region'), table_name='superstore_sales')
    op.drop_index(op.f('ix_superstore_sales_city'), table_name='superstore_sales')
    op.drop_index(op.f('ix_superstore_sales_category'), table_name='superstore_sales')
    op.alter_column('superstore_sales', 'postal_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
